version: '3.6'
services:
  rails:
    build:
      context: .
    depends_on:
      - webpacker
      - postgres
    volumes:
      - $PWD:/app
    ports:
     - "3000:3000"
    command: bundle exec rails s
    env_file:
      - .env_rails
      - .env
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PWD=password
  webpacker:
    build:
      context: .
    volumes:
      - $PWD:/app
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    env_file:
      - .env_rails
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  postgres:
    image: "postgres:10.3-alpine"
    ports: ["5432:5432"]
    volumes:
      - $PWD/db/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$APP_NAME
      - POSTGRES_PASSWORD=password
